export const servers = [
  {
    id: 1,
    name: "Craftopia",
    ip: "192.168.1.1",
    version: "1.20.1",
    mode: "Survival",
    difficulty: "Hard",
    maxPlayers: 20,
    pvp: true,
  },
  {
    id: 2,
    name: "Skyland Adventures",
    ip: "203.0.113.5",
    version: "1.19.3",
    mode: "Adventure",
    difficulty: "Normal",
    maxPlayers: 15,
    pvp: false,
  },
  {
    id: 3,
    name: "PixelVerse",
    ip: "198.51.100.23",
    version: "1.18.2",
    mode: "Creative",
    difficulty: "Peaceful",
    maxPlayers: 25,
    pvp: false,
  },
  {
    id: 4,
    name: "EpicWars",
    ip: "203.0.113.77",
    version: "1.20.1",
    mode: "Survival",
    difficulty: "Normal",
    maxPlayers: 30,
    pvp: true,
  },
  {
    id: 5,
    name: "MysticCraft",
    ip: "198.51.100.11",
    version: "1.19",
    mode: "Adventure",
    difficulty: "Easy",
    maxPlayers: 10,
    pvp: false,
  },
  {
    id: 6,
    name: "NetherQuest",
    ip: "192.168.0.45",
    version: "1.20",
    mode: "Survival",
    difficulty: "Hard",
    maxPlayers: 5,
    pvp: true,
  },
  {
    id: 7,
    name: "Blocky Realms",
    ip: "198.51.100.55",
    version: "1.18.1",
    mode: "Creative",
    difficulty: "Normal",
    maxPlayers: 15,
    pvp: false,
  },
  {
    id: 8,
    name: "BedWars Arena",
    ip: "203.0.113.90",
    version: "1.20.1",
    mode: "Adventure",
    difficulty: "Normal",
    maxPlayers: 25,
    pvp: true,
  },
  {
    id: 9,
    name: "VillageCraft",
    ip: "192.0.2.60",
    version: "1.19.2",
    mode: "Survival",
    difficulty: "Peaceful",
    maxPlayers: 12,
    pvp: false,
  },
  {
    id: 10,
    name: "Adventure Realm",
    ip: "198.51.100.200",
    version: "1.18.2",
    mode: "Adventure",
    difficulty: "Hard",
    maxPlayers: 20,
    pvp: true,
  },
];
